trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  # Configurar una sola versión de Python (sin matriz)
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'  # Elige una versión específica de Python
    displayName: 'Usar Python 3.7'

  # Instalar dependencias
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Instalar dependencias'

  # Ejecutar pruebas
  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'Ejecutar pruebas con Pytest'
